// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO9HWT2J8PzJI0UsXokxjDskwYwav4OL8',
    appId: '1:907071080385:web:06a2e8340425ccf0d7d140',
    messagingSenderId: '907071080385',
    projectId: 'sms-firebase-f0785',
    authDomain: 'sms-firebase-f0785.firebaseapp.com',
    storageBucket: 'sms-firebase-f0785.appspot.com',
    measurementId: 'G-T9BQRN9X6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5OQ237li87DTyT2guFuwKrloLvRR-0Tw',
    appId: '1:907071080385:android:bbadcf3dc3da7b32d7d140',
    messagingSenderId: '907071080385',
    projectId: 'sms-firebase-f0785',
    storageBucket: 'sms-firebase-f0785.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw7Wmp9UswoVvvFssYzODxGbGfpXVzjM4',
    appId: '1:907071080385:ios:48d3832d2e46bd9bd7d140',
    messagingSenderId: '907071080385',
    projectId: 'sms-firebase-f0785',
    storageBucket: 'sms-firebase-f0785.appspot.com',
    iosClientId: '907071080385-2f5d976ha99s1bakr9i6he2ttd1kabbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.otpFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw7Wmp9UswoVvvFssYzODxGbGfpXVzjM4',
    appId: '1:907071080385:ios:48d3832d2e46bd9bd7d140',
    messagingSenderId: '907071080385',
    projectId: 'sms-firebase-f0785',
    storageBucket: 'sms-firebase-f0785.appspot.com',
    iosClientId: '907071080385-2f5d976ha99s1bakr9i6he2ttd1kabbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.otpFlutter',
  );
}
